// This file is generated by Slice Machine. Update with care!

import SliceHeadline from './SliceHeadline'
import SliceImage from './SliceImage'
import SliceImageWContent from './SliceImageWContent'
import SliceLinksRibbon from './SliceLinksRibbon'
import SliceMetas from './SliceMetas'
import SliceVideo from './SliceVideo'

export {
  SliceHeadline,
  SliceImage,
  SliceImageWContent,
  SliceLinksRibbon,
  SliceMetas,
  SliceVideo
}

export const components = {
  slice_headline: SliceHeadline,
  slice_image: SliceImage,
  slice_image_w_content: SliceImageWContent,
  slice_links_ribbon: SliceLinksRibbon,
  slice_metas: SliceMetas,
  slice_video: SliceVideo
}
